// screens/constants.js

export const COUNTRIES = [
    { code: "AF", name: "Afganistan 🇦🇫" },
    { code: "DE", name: "Almanya 🇩🇪" },
    { code: "US", name: "ABD 🇺🇸" },
    { code: "AO", name: "Angola 🇦🇴" },
    { code: "AR", name: "Arjantin 🇦🇷" },
    { code: "AL", name: "Arnavutluk 🇦🇱" },
    { code: "AU", name: "Avustralya 🇦🇺" },
    { code: "AT", name: "Avusturya 🇦🇹" },
    { code: "AZ", name: "Azerbaycan 🇦🇿" },
    { code: "AE", name: "BAE 🇦🇪" },
    { code: "BE", name: "Belçika 🇧🇪" },
    { code: "BD", name: "Bangladeş 🇧🇩" },
    { code: "BA", name: "Bosna Hersek 🇧🇦" },
    { code: "BR", name: "Brezilya 🇧🇷" },
    { code: "BG", name: "Bulgaristan 🇧🇬" },
    { code: "DZ", name: "Cezayir 🇩🇿" },
    { code: "CN", name: "Çin 🇨🇳" },
    { code: "DK", name: "Danimarka 🇩🇰" },
    { code: "ID", name: "Endonezya 🇮🇩" },
    { code: "MA", name: "Fas 🇲🇦" },
    { code: "PS", name: "Filistin PS" },
    { code: "FI", name: "Finlandiya 🇫🇮" },
    { code: "FR", name: "Fransa 🇫🇷" },
    { code: "GH", name: "Gana 🇬🇭" },
    { code: "KR", name: "Güney Kore 🇰🇷" },
    { code: "GE", name: "Gürcistan 🇬🇪" },
    { code: "IN", name: "Hindistan 🇮🇳" },
    { code: "NL", name: "Hollanda 🇳🇱" },
    { code: "IQ", name: "Irak 🇮🇶" },
    { code: "GB", name: "İngiltere 🇬🇧" },
    { code: "IR", name: "İran 🇮🇷" },
    { code: "ES", name: "İspanya 🇪🇸" },
    { code: "SE", name: "İsveç 🇸🇪" },
    { code: "CH", name: "İsviçre 🇨🇭" },
    { code: "IT", name: "İtalya 🇮🇹" },
    { code: "JP", name: "Japonya 🇯🇵" },
    { code: "CA", name: "Kanada 🇨🇦" },
    { code: "QA", name: "Katar 🇶🇦" },
    { code: "KZ", name: "Kazakistan 🇰🇿" },
    { code: "KG", name: "Kırgızistan 🇰🇬" },
    { code: "CO", name: "Kolombiya 🇨🇴" },
    { code: "KW", name: "Kuveyt 🇰🇼" },
    { code: "LY", name: "Libya 🇱🇾" },
    { code: "LB", name: "Lübnan 🇱🇧" },
    { code: "HU", name: "Macaristan 🇭🇺" },
    { code: "MK", name: "Makedonya 🇲🇰" },
    { code: "MY", name: "Malezya 🇲🇾" },
    { code: "EG", name: "Mısır 🇪🇬" },
    { code: "NG", name: "Nijerya 🇳🇬" },
    { code: "NO", name: "Norveç 🇳🇴" },
    { code: "UZ", name: "Özbekistan 🇺🇿" },
    { code: "PK", name: "Pakistan 🇵🇰" },
    { code: "PL", name: "Polonya 🇵🇱" },
    { code: "PT", name: "Portekiz 🇵🇹" },
    { code: "RO", name: "Romanya 🇷🇴" },
    { code: "RU", name: "Rusya 🇷🇺" },
    { code: "SN", name: "Senegal 🇸🇳" },
    { code: "SO", name: "Somali 🇸🇴" },
    { code: "SY", name: "Suriye 🇸🇾" },
    { code: "SA", name: "Suudi Arabistan 🇸🇦" },
    { code: "TJ", name: "Tacikistan 🇹🇯" },
    { code: "TH", name: "Tayland 🇹🇭" },
    { code: "TN", name: "Tunus 🇹🇳" },
    { code: "TR", name: "Türkiye 🇹🇷" },
    { code: "TM", name: "Türkmenistan 🇹🇲" },
    { code: "UA", name: "Ukrayna 🇺🇦" },
    { code: "JO", name: "Ürdün 🇯🇴" },
    { code: "VN", name: "Vietnam 🇻🇳" },
    { code: "YE", name: "Yemen 🇾🇪" },
    { code: "GR", name: "Yunanistan 🇬🇷" }
  ];
  
  export const LANGUAGES = [
    { code: "TR", name: "Türkçe" },
    { code: "DE", name: "Almanca" },
    { code: "AR", name: "Arapça" },
    { code: "SQ", name: "Arnavutça" },
    { code: "AZ", name: "Azerice" },
    { code: "BS", name: "Boşnakça" },
    { code: "BG", name: "Bulgarca" },
    { code: "ZH", name: "Çince" },
    { code: "ID", name: "Endonezce" },
    { code: "FA", name: "Farsça" },
    { code: "FR", name: "Fransızca" },
    { code: "KA", name: "Gürcüce" },
    { code: "HI", name: "Hintçe" },
    { code: "NL", name: "Hollandaca" },
    { code: "EN", name: "İngilizce" },
    { code: "ES", name: "İspanyolca" },
    { code: "IT", name: "İtalyanca" },
    { code: "JA", name: "Japonca" },
    { code: "KK", name: "Kazakça" },
    { code: "KY", name: "Kırgızca" },
    { code: "KO", name: "Korece" },
    { code: "KU", name: "Kürtçe" },
    { code: "MS", name: "Malayca" },
    { code: "UZ", name: "Özbekçe" },
    { code: "PS", name: "Peştuca" },
    { code: "PT", name: "Portekizce" },
    { code: "RU", name: "Rusça" },
    { code: "SO", name: "Somalice" },
    { code: "TK", name: "Türkmence" },
    { code: "UK", name: "Ukraynaca" },
    { code: "UR", name: "Urduca" },
    { code: "EL", name: "Yunanca" }
  ];